//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibleTaggingUtil.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class OsisFileGeneration : global::System.Configuration.ApplicationSettingsBase {
        
        private static OsisFileGeneration defaultInstance = ((OsisFileGeneration)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OsisFileGeneration())));
        
        public static OsisFileGeneration Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseDisambiguatedStrong {
            get {
                return ((bool)(this["UseDisambiguatedStrong"]));
            }
            set {
                this["UseDisambiguatedStrong"] = value;
            }
        }
    }
}
